#!/bin/bash
#PBS -l nodes=1:atreides:ppn=1
#PBS -o singlejets.out
#PBS -v PBS_O_SHELL=/bin/bash
#PBS -e singlejets.err
#PBS -V
#PBS -N singlejets
#PBS -t 101-200

cd /homes/jorgen/clinty/junkdir/MARTINI/main
./main_singlejets $PBS_ARRAYID
