#!/bin/bash
#PBS -o nohup_MARTINI_main9.out
#PBS -v PBS_O_SHELL=/bin/bash
#PBS -e errors_MARTINI_main9.out
#PBS -V
#PBS -N MARTINI_main9

cd /homes/jorgen/clinty/junkdir/MARTINI/main
c=1
while [ $c -le 5 ]
do
    ./main9 $c setup_main9.dat
    (( c++ ))
done
