#!/bin/bash
#PBS -o nohup_MARTINI_main_jet_profile_lowersettings.out
#PBS -v PBS_O_SHELL=/bin/bash
#PBS -e errors_MARTINI_main_jet_profile_lowersettings.out
#PBS -V
#PBS -N MARTINI_main_jet_profile_lowersettings
#PBS -l walltime=30:00:00

writing_dir=noname

cd /home/clintfy/MARTINI/main
./main_jet_profile_lowersettings $main_jet_profile_lowersettings_var1 setup_main_jet_profile_lowersettings.dat $writing_dir
