#!/bin/bash
#PBS -o nohup_MARTINI_main_CMS.out
#PBS -v PBS_O_SHELL=/bin/bash
#PBS -e errors_MARTINI_main_CMS.out
#PBS -V
#PBS -N MARTINI_main_CMS

cd /homes/jorgen/clinty/junkdir/MARTINI/main
./main_CMS_dNdA $main_CMS_dNdA_var_1 setup_main_CMS_dNdA.dat
