#!/bin/bash
#PBS -o nohup_MARTINI_main8.out
#PBS -v PBS_O_SHELL=/bin/bash
#PBS -e errors_MARTINI_main8.out
#PBS -V
#PBS -N MARTINI_main8

cd /homes/jorgen/clinty/junkdir/MARTINI/main
c=351
while [ $c -le 353 ]
do
    ./main8 $c setup_main8.dat
    (( c++ ))
done
