#!/bin/bash
#PBS -o nohup_MARTINI_main_ALICE_charged_alpha25.out
#PBS -v PBS_O_SHELL=/bin/bash
#PBS -e errors_MARTINI_main_ALICE_charged_alpha25.out
#PBS -V
#PBS -N MARTINI_main_ALICE_charged_alpha25

cd /homes/jorgen/clinty/junkdir/MARTINI/main
./main_ALICE_charged_alpha25 $main_ALICE_charged_alpha25_var1 setup_main_ALICE_charged_alpha25.dat
