#!/bin/bash
#PBS -l nodes=1:atreides:ppn=1
#PBS -o main_HQ_JPsiYields.out
#PBS -v PBS_O_SHELL=/bin/bash
#PBS -e main_HQ_JPsiYields.err
#PBS -V
#PBS -N main_HQ_JPsiYields
#PBS -t 1-200

cd /homes/jorgen/clinty/junkdir/MARTINI/main_HQ
./main_HQ_JPsiYields $PBS_ARRAYID
